# .streamlit/secrets.toml
OPENAI_API_KEY="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"
